// react/calculadora/src/main/Calculator.jsx
import React, { Component } from "react";
import "./Calculator.css";

import Button from "../components/Button";
import Display from "../components/Display";

const inicialState = {
  displayValue: "0",
  clearDisplay: false,
  operation: null,
  values: [0, 0],
  currentIndex: 0,
};

export default class Calculator extends Component {
  state = { ...inicialState };

  constructor(props) {
    super(props);
    /* opcao 2 */
    this.setOperation = this.setOperation.bind(this);
  }

  clearMemory() {
    this.setState({ ...inicialState });
  }

  setOperation(operation) {
    if (this.state.currentIndex === 0) {
      this.setState({
        currentIndex: 1,
        clearDisplay: true,
        operation: operation,
      });
    } else {
      const equals = operation === '='
      const currentOperation = this.state.operation

      const values = [...this.state.values]
      try {
        values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`)
      } catch(e) {
        values[0] = this.state.values[0]
      }
      values[1] = 0

      this.setState({
        displayValue: values[0],
        operation: equals ? null: operation,
        current: equals ? 0 : 1,
        clearDisplay: !equals,
        values: values
      })
    }
  }

  addDigit(digit) {
    if (digit === "." && this.state.displayValue.includes(".")) {
      return;
    }

    const clearDisplay =
      this.state.displayValue === "0" || this.state.clearDisplay;

    const currentValue = clearDisplay ? "" : this.state.displayValue;
    const newDisplayValue = currentValue + digit;
    this.setState({ displayValue: newDisplayValue, clearDisplay: false });

    if (digit !== ".") {
      const index = this.state.currentIndex;
      const newValue = parseFloat(newDisplayValue);
      const values = [...this.state.values];
      values[index] = newValue;
      this.setState({ values: values });
      console.log(values);
    }
  }

  render() {
    /* opcao 3 */
    const addDigit = (digit) => this.addDigit(digit);

    return (
      <div className="calculator">
        <Display value={this.state.displayValue} />
        {/* opcao 1 */}
        <Button label="AC" click={() => this.clearMemory()} triple />
        {/* opcao 2 */}
        <Button label="/" click={this.setOperation} operation />
        {/* opcao 3 */}
        <Button label="7" click={addDigit} />
        <Button label="8" click={addDigit} />
        <Button label="9" click={addDigit} />
        <Button label="*" click={this.setOperation} operation />
        <Button label="4" click={addDigit} />
        <Button label="5" click={addDigit} />
        <Button label="6" click={addDigit} />
        <Button label="-" click={this.setOperation} operation />
        <Button label="1" click={addDigit} />
        <Button label="2" click={addDigit} />
        <Button label="3" click={addDigit} />
        <Button label="+" click={this.setOperation} operation />
        <Button label="0" click={addDigit} double />
        <Button label="." click={addDigit} />
        <Button label="=" click={this.setOperation} operation />
      </div>
    );
  }
}

// vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
    <Display :value="displayValue" />
    <Button label="AC" @on-calc-button-click="clearMemory" triple />
    <Button label="/" @on-calc-button-click="setOperation" operation />
    <Button label="7" @on-calc-button-click="addDigit" />
    <Button label="8" @on-calc-button-click="addDigit" />
    <Button label="9" @on-calc-button-click="addDigit" />
    <Button label="*" @on-calc-button-click="setOperation" operation />
    <Button label="4" @on-calc-button-click="addDigit" />
    <Button label="5" @on-calc-button-click="addDigit" />
    <Button label="6" @on-calc-button-click="addDigit" />
    <Button label="-" @on-calc-button-click="setOperation" operation />
    <Button label="1" @on-calc-button-click="addDigit" />
    <Button label="2" @on-calc-button-click="addDigit" />
    <Button label="3" @on-calc-button-click="addDigit" />
    <Button label="+" @on-calc-button-click="setOperation" operation />
    <Button label="0" @on-calc-button-click="addDigit" double />
    <Button label="." @on-calc-button-click="addDigit" />
    <Button label="=" @on-calc-button-click="setOperation" operation />
  </div>
</template>

<script>
import Display from "../components/Display";
import Button from "../components/Button";
export default {
  data: function() {
    return {
      displayValue: "0",
      clearDisplay: false,
      operation: null,
      values: [0, 0],
      currentIndex: 0,
    };
  },
  components: { Button, Display },
  methods: {
    clearMemory() {
      Object.assign(this.$data, this.$options.data());
    },
    setOperation(operation) {
      if (this.currentIndex === 0) {
        this.operation = operation;
        this.currentIndex = 1;
        this.clearDisplay = true;
      } else {
        const equals = operation === "=";
        const currentOperation = this.operation;

        try {
          this.values[0] = eval(
            `${this.values[0]} ${currentOperation} ${this.values[1]}`
          );
        } catch (e) {
          this.$emit("onError", e);
        }

        this.values[1] = 0;
        this.displayValue = this.values[0];
        this.operation = equals ? null : operation;
        this.currentIndex = equals ? 0 : 1;
        this.clearDisplay = !equals;
      }
    },
    addDigit(n) {
      if (n === "." && this.displayValue.includes(".")) {
        return;
      }

      const clearDisplay = this.displayValue === "0" || this.clearDisplay;
      const currentValue = clearDisplay ? "" : this.displayValue;
      const displayValue = currentValue + n;

      this.displayValue = displayValue;
      this.clearDisplay = false;

      // Alternativa 1
      this.values[this.currentIndex] = displayValue;

      // Alternativa 2
    //   if (n !== ".") {
    //     const index = this.currentIndex;
    //     const newValue = parseFloat(displayValue);
    //     this.values[index] = newValue;
    //   }
    },
  },
};
</script>

<style>
.calculator {
  height: 320px;
  width: 235px;
  border-radius: 5px;
  overflow: hidden;

  display: grid;
  grid-template-columns: repeat(4, 25%);
  grid-template-rows: 1fr repeat(5, 48px);
}
</style>
